baseURL = 'https://schwidola0607.github.io/khoa-blog/'
languageCode = 'en-us'
title = "Khoa's blog"
theme = 'hugo-bearblog'

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Configure blog permalinks (Bearblog-style URLs)
[permalinks]
  blog = "/:slug/"

[params]
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

[caches]
  [caches.images]
    dir = ':cacheDir/images'
